#include <stdio.h>
#include <time.h>

/*


Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

*/

int f0(void) {
  int x0 = 1;
  int x1 = 2;

  int soma = 0;

  while (x0 < 4000000) {
    if (x0 % 2 == 0) {
      soma = soma + x0;
    }

    int tmp = x0;
    x0 = x1;
    x1 = tmp + x1;
  }

  return soma;
}

int f1(void) {
  int x = 1;
  int y = 2;
  int z = x + y; // Subtle bug.

  int soma = 0;

  while (z <= 4000000) {
    if (z % 2 == 0) {
      soma = soma + z;
    }
    x = y;
    y = z;
    z = x + y;
  }

  return soma;
}

// The Fibonacci sequence follows this pattern:
//                                                                          
//    ODD, EVEN, ODD, ODD, EVEN, ODD, ODD, EVEN, ...
//                                                                          
// We take advantage of this by starting with two and stepping multiple times
// at once.
int f2(void) {
  int x0 = 2;
  int x1 = 3;

  int soma = 0;

  while (x0 < 4000000) {
    soma = soma + x0;

    int tmp = x0;
    x0 = tmp + 2 * x1;
    x1 = 2 * tmp + 3 * x1;
  }

  return soma;
}

int main(void) {
  clock_t start, end;

  start = clock();
  for (int i = 0; i < 10000000; i = i + 1) f0();
  end = clock();
  printf("f0: %f seconds\n", (float)(end - start) / CLOCKS_PER_SEC);

  start = clock();
  for (int i = 0; i < 10000000; i = i + 1) f2();
  end = clock();
  printf("f1: %f seconds\n", (float)(end - start) / CLOCKS_PER_SEC);

  printf("%d\n", f2());

  return 0;
}
